export type AttemptStatus =
  | "survived"
  | "partial"
  | "failed"
  | "blocked"
  | "retracted";

export type Attempt = {
  method: string;
  question: string;
  result: string;
  implication: string;
  status: AttemptStatus;
  artifact?: string;
};

export type Phase = {
  title: string;
  scope: string;
  attempts: Attempt[];
};

export const phases: Phase[] = [
  {
    title: "Body recovery and reusable motion",
    scope: "Can ordinary or calibrated video produce a body artifact that remains useful outside the source camera?",
    attempts: [
      {
        method: "MediaPipe Pose",
        question: "Is cheap 2D pose enough for serve timing and gross arm motion?",
        result: "Ran across tennis clips. Fast and useful for 2D arm diagnostics, but depth, feet, hands, racket, ball, and world motion were not reliable.",
        implication: "Keep as a capture and phase diagnostic; never call it a 3D serve reconstruction.",
        status: "partial",
      },
      {
        method: "RTMPose-m head-to-head",
        question: "Would a newer 2D pose model materially improve the retained MediaPipe layer?",
        result: "On the same clip, MediaPipe ran at 104 fps versus 4.81 fps and had 59% lower wrist-jerk noise; wrist-speed correlation was 0.895 and both found the same contact frame.",
        implication: "The practical 2D layer was not the blocker. Retain MediaPipe rather than swapping models for novelty.",
        status: "survived",
      },
      {
        method: "MediaPipe Heavy + world landmarks",
        question: "Could the discarded world-landmark output recover axial sequencing?",
        result: "Arm-chain peaks reproduced within one frame, but the axial channels failed the observability and full-versus-heavy agreement gates and were emitted as null.",
        implication: "Arm timing survives; monocular axial rotation does not.",
        status: "partial",
      },
      {
        method: "GEM-X / SOMA on CalTennis",
        question: "Can one public monocular serve become a stable full-body moving mesh?",
        result: "Produced a 71-frame fixed-topology body and orbitable GLB with body and hands.",
        implication: "Best executed monocular body baseline; still not grip, racket, ball, contact, or metric depth truth.",
        status: "partial",
      },
      {
        method: "GEM-X / SOMA on Djokovic and Medvedev",
        question: "Does the monocular body route generalize beyond one CalTennis clip?",
        result: "Produced two additional moving body outputs. Identity stayed coherent enough to inspect, while sport-object layers remained absent.",
        implication: "The body route repeats; the missing racket/ball geometry repeats too.",
        status: "partial",
      },
      {
        method: "Calibrated X2/X4 body reprojection",
        question: "Is the plausible monocular body spatially consistent in a synchronized second view?",
        result: "Body reached 3.01 px median reprojection across 2,184 observations.",
        implication: "The body layer passed its spatial test. Additional body compute was no longer the highest-value next step.",
        status: "survived",
      },
      {
        method: "AIMoCap built-in tennis sample",
        question: "Can a hosted route quickly return an editable tennis rig?",
        result: "The provided sample yielded a 205-frame, 63-bone FBX. A custom Jerry-source reconstruction was never proved.",
        implication: "Useful production reference, not evidence about our footage.",
        status: "partial",
      },
      {
        method: "GVHMR hosted custom inference",
        question: "Could a world-grounded monocular body challenger replace GEM-X?",
        result: "The hosted custom inference returned HTTP 500 and produced no accepted artifact.",
        implication: "No output means no basis to outrank the executed baseline.",
        status: "failed",
      },
      {
        method: "SAM-Body4D local setup",
        question: "Could temporal body repair produce a more stable same-source body?",
        result: "The code path was audited, but gated assets and the CUDA-oriented stack prevented a same-source run.",
        implication: "Credible literature candidate, but not an executed result in this project.",
        status: "blocked",
      },
      {
        method: "Bath 4D_56 marker reconstruction",
        question: "Can a public measured serve replace inference for body and racket motion?",
        result: "Parsed 42 serve files. Selected 4D_56 has 301/301 finite frames at 180 Hz; three racket-marker candidates remain rigid within 20 mm throughout.",
        implication: "Strongest measured body+racket surrogate; it lacks raw video, camera calibration, ball, impact, and grip truth.",
        status: "survived",
        artifact: "/media/bath-4d56-two-view.mp4",
      },
      {
        method: "Bath marker-to-skeleton mapping",
        question: "Could the anonymous marker array become a fully articulated athlete automatically?",
        result: "The release omitted marker names and the available mapping stopped at a proxy marker map rather than a defensible full skeleton.",
        implication: "Measured trajectories survive; anatomical labels and articulation require new evidence.",
        status: "failed",
      },
      {
        method: "Bath skinned retarget",
        question: "Can the measured marker motion drive a standard skinned athlete without distortion?",
        result: "The local-rotation retarget missed the wrists by 119.2 mm and 89.6 mm median and was rejected.",
        implication: "Use the measured marker truth directly; the stylized player is presentation, not recovered anatomy.",
        status: "failed",
      },
      {
        method: "Bath Serve Study presentation",
        question: "Can measured motion still become a watchable teaching artifact after retarget failure?",
        result: "A 118-frame toss→contact→flight→bounce sequence shipped in rear, side, and orbit views with the stylized fallback explicitly labeled.",
        implication: "Presentation can clarify measured timing without upgrading the body or ball to measurement.",
        status: "survived",
        artifact: "/media/bath-4d56-two-view.mp4",
      },
    ],
  },
  {
    title: "Racket, ball, grip, and contact",
    scope: "Can the small fast objects be recovered independently instead of being attached to a plausible body?",
    attempts: [
      {
        method: "RacketVision five-point racket fit",
        question: "Can five racket keypoints yield a rigid racket pose on CalTennis?",
        result: "The synchronized fit reached 17.59 px median reprojection and 23.53 px at contact, failing the acceptance gate.",
        implication: "Keypoints are proposals, not an accepted racket SE(3) track.",
        status: "failed",
      },
      {
        method: "BallTrack at published threshold",
        question: "Can the tennis-specific tracker recover the ball through contact?",
        result: "Found only 3 of 131 frames on the first clip and missed contact.",
        implication: "The released tennis-specific route did not solve this source.",
        status: "failed",
      },
      {
        method: "BallTrack low-threshold retry",
        question: "Was the failure only a confidence cutoff?",
        result: "Lowering the threshold added static false positives without recovering trustworthy contact evidence.",
        implication: "Threshold tuning could not substitute for better observations.",
        status: "failed",
      },
      {
        method: "DexGraspNet + MANO handle fitting",
        question: "Can a generic grasp prior create a credible tennis grip?",
        result: "Optimization improved numeric scores while rendered hands penetrated the handle, opened, or left gaps.",
        implication: "A plausible prior is not athlete-specific grip measurement.",
        status: "failed",
      },
      {
        method: "Alcaraz manual evidence composite",
        question: "What can careful source-camera annotation establish without pretending to solve 3D?",
        result: "Produced 61 reviewed arm frames, 54 racket silhouettes, observed post-contact ball positions, and one fixed-camera teaching composite.",
        implication: "Useful 2D teaching evidence; not a reusable any-angle serve.",
        status: "survived",
      },
      {
        method: "Constant hand-socket-to-racket transform",
        question: "Can separately plausible body and racket layers be made coherent with one rigid attachment?",
        result: "Missed by 207.46 mm median position and 82.25° median orientation.",
        implication: "The composed layers were structurally incompatible.",
        status: "failed",
      },
      {
        method: "Racket-first authored-grip fit",
        question: "If racket motion stays fixed, can one local wrist point explain 61 observed wrist positions?",
        result: "Only 7/61 frames met the ≤8 px gate; median error was 15.45 px and max was 57.79 px.",
        implication: "Do not export or tune another authored grip from the same evidence.",
        status: "failed",
      },
      {
        method: "Wrist-first flipped-anchor fit",
        question: "If the arm is exact, can the racket follow without breaking continuity?",
        result: "Arm clicks were exact, but arm steps exceeded 20°, racket error reached 46.40 px median, and two face-normal flips remained.",
        implication: "The opposite hierarchy failed too; a third monocular composition was closed.",
        status: "failed",
      },
      {
        method: "TrackNetV4 / contact-ball attempt",
        question: "Can a tennis ball detector establish the impact transition on the Alcaraz window?",
        result: "The output could not support a single-frame physical-impact claim; the final page retained only observed 2D positions and a contact bracket.",
        implication: "Contact remains a bracket, not a detected instant.",
        status: "failed",
      },
      {
        method: "Four-stage synthetic contact lab",
        question: "Can compression, felt, stringbed, and coupled impact be modeled transparently?",
        result: "Passed 37 numerical checks and four runtime invariants on declared synthetic parameters.",
        implication: "Useful mechanics sandbox; it explains mechanisms but identifies no real stroke until parameters are measured.",
        status: "survived",
      },
    ],
  },
  {
    title: "Source quality and capture geometry",
    scope: "Would a better existing clip, more compute, or a different capture contract remove the missing evidence?",
    attempts: [
      {
        method: "15 local source-window screen",
        question: "Does any available tennis window preserve cadence, racket size, contact, and useful view together?",
        result: "0/15 passed all four frozen gates; none reached the ≥80% unique-adjacent-frame cadence requirement.",
        implication: "Another convenient internet clip was not the answer.",
        status: "failed",
      },
      {
        method: "Seven external high-speed candidates",
        question: "Do stronger named sources unlock a full serve or contact exhibit?",
        result: "All 4,272 delivered frames were reviewed; 0/7 passed the full-serve profile and 0/7 passed the contact-exhibit profile.",
        implication: "High-speed branding did not guarantee recoverable cadence or geometry.",
        status: "failed",
      },
      {
        method: "More-body-compute fork",
        question: "Would renting more GPU fix the current failure?",
        result: "Closed because body reprojection already passed while racket face, palm-handle relation, and contact evidence remained absent.",
        implication: "Compute cannot invent unrecorded geometry.",
        status: "failed",
      },
      {
        method: "Owned-capture intake validator",
        question: "Could synchronized 240 fps rear/side footage be accepted before expensive inference?",
        result: "Built fail-closed checks for native media, synchronization, calibration, marker visibility, rights, and evidence windows; no qualifying owned capture existed.",
        implication: "The required next input is explicit and testable, not a vague request for better video.",
        status: "blocked",
      },
      {
        method: "Synthetic self-calibration test",
        question: "Can skeleton geometry remove the need for a known calibration object?",
        result: "At 1–3 px pose noise, recovered camera pose was off by 6–8°, about one metre lateral error at seven metres.",
        implication: "Retain a known-length object in both views; self-calibration was not obviously safe.",
        status: "failed",
      },
      {
        method: "Salvage test suite",
        question: "Should imperfect footage be discarded or still analyzed?",
        result: "Three of five documented failures stayed analyzable. Cropping the racket and severe backlighting were the decisive losses; 120 fps, sub-1080p, portrait, dim light, and split takes were not automatic discards.",
        implication: "Send flawed footage and annotate the flaw; do not destroy evidence by reflexively reshooting.",
        status: "survived",
      },
      {
        method: "Gravity-clock recovery",
        question: "Can unknown slow-motion playback rate be inferred from the corpus after capture?",
        result: "Two independent recovery routes failed; physics fitting needs the clock that the internet copies no longer preserve.",
        implication: "Any speed, duration, sequence timing, or physics prior needs verified native frame timing.",
        status: "failed",
      },
      {
        method: "Toss detector escalation",
        question: "Can three automatic ball-detection methods recover toss apexes?",
        result: "Validation collapsed from 1/7 to 0/4 to 0/1; the top-scoring detection was a ceiling light. The registered result was void.",
        implication: "Eye-and-grid became the instrument; automated detection did not earn the measurement.",
        status: "failed",
      },
      {
        method: "Manual toss-apex adjudication",
        question: "What clockless serve quantity can the old corpus still answer?",
        result: "For seven adjudicated kick serves, 4/7 apexes were on the non-hitting side and median x was −0.232 torso lengths; the slice comparison lacked enough valid rows.",
        implication: "A small measured descriptive result survives; the registered kick-vs-slice comparison does not.",
        status: "partial",
      },
    ],
  },
  {
    title: "Simulation, controllers, and generated presentation",
    scope: "Can physics or generation make the result useful without being confused with observation?",
    attempts: [
      {
        method: "Authored ball-flight simulator",
        question: "Can a declared physics ball provide a coherent teaching layer?",
        result: "Passed its teaching gates at 6.725 px median / 19.234 px p95 reprojection, 0.0511 m net clearance, and an in-box first bounce.",
        implication: "Useful as authored physics; launch and spin remain unmeasured.",
        status: "survived",
      },
      {
        method: "RIFE interpolation",
        question: "Can sparse presentation frames be made easier to watch?",
        result: "Produced 13/13 deterministic midpoints in 19 seconds, continuously labeled as interpolated and not captured.",
        implication: "Presentation-only pixels stay outside evidence receipts.",
        status: "survived",
      },
      {
        method: "SONIC controller",
        question: "Can a released physics controller run locally on the Mac?",
        result: "Environment and assets loaded, but the Linux/CUDA/TensorRT controller produced zero controlled steps.",
        implication: "Dead on this machine; do not treat setup success as a motion result.",
        status: "failed",
      },
      {
        method: "ProtoMotions CPU policy",
        question: "Can an open physics policy execute locally and accept the recovered athlete later?",
        result: "Ran 19,801 MuJoCo steps across 58 motions with 0 invalid states and 0.965517 success; the Alcaraz target stopped because its GLB had no skin, bones, or joint rotations.",
        implication: "Controller works; articulation transport is the wall.",
        status: "partial",
      },
      {
        method: "DeepMimic Apple-CPU port",
        question: "Can the older controller provide a second local feasibility check?",
        result: "Engine, checkpoint, and renderer ran; one diagnostic stayed finite, but the five-minute repeat diverged with 3,715 non-finite markers.",
        implication: "Not stable enough and not tennis-specific; no training run justified.",
        status: "failed",
      },
      {
        method: "TrajectoryCrafter / cloud generation",
        question: "Can a generative video route supply missing camera or motion evidence?",
        result: "Quota and propagation tests did not produce an evidence-safe, source-faithful reconstruction.",
        implication: "Generated views cannot become measurements.",
        status: "failed",
      },
      {
        method: "LTX-Video local path",
        question: "Can local video generation run inside the available Apple-memory budget?",
        result: "The PyTorch/MPS route exceeded the practical memory envelope and was stopped.",
        implication: "Framework and memory wall; no evidence artifact.",
        status: "failed",
      },
      {
        method: "SeedVR2 3B restoration",
        question: "Can local restoration clarify a 6000 fps contact reference without changing evidence?",
        result: "Ran in 6.44 seconds at 4.05 GB peak memory, sharpened the frame, and invented ball-seam texture.",
        implication: "Useful only for presentation; rejected as evidence.",
        status: "failed",
      },
    ],
  },
  {
    title: "Ball and racket tracking progression",
    scope: "A controlled sequence of same-source tests: change one observation or tracking primitive, inspect every output, then pivot only from the failure.",
    attempts: [
      {
        method: "Three-clip released-model bakeoff",
        question: "Would clearer real sources make BallTrack, RacketPose, MediaPipe, and hand tracking work unchanged?",
        result: "Only 1/15 sources passed the initial readability gate. Ball and racket models still failed; MediaPipe passed gross 2D arm alignment on the clearest clip only.",
        implication: "Source quality helped body pose but did not rescue the small-object models.",
        status: "failed",
      },
      {
        method: "CoTracker3 Offline ball tracking",
        question: "Can a generic point tracker retain ball center through racket overlap?",
        result: "Passed on the 76-frame clear clip: 54/57 verified ball frames, 0.99 px median, 2.68 px p90, 1.87 px at overlap, and zero false points after exit.",
        implication: "Strongest surviving source-camera ball observation on a clear clip.",
        status: "survived",
        artifact: "/media/accepted-2d-evidence.mp4",
      },
      {
        method: "SAM 2.1 Tiny racket silhouette",
        question: "Can a generic segmenter retain the racket as a 2D mask?",
        result: "Stayed attached for 76/76 frames on the clear clip; its ball mask failed the center gate.",
        implication: "Useful 2D silhouette on readable inputs; not rigid pose or general tracking.",
        status: "survived",
        artifact: "/media/accepted-2d-evidence.mp4",
      },
      {
        method: "CoTracker3 replication on two harder clips",
        question: "Does the ball result survive occlusion, clipping, and repeated slow motion?",
        result: "Failed one clipped/overlap case and reached only 41/55 attached on the repeated-slow-motion case.",
        implication: "The clear-clip win did not establish general ball tracking.",
        status: "failed",
      },
      {
        method: "SAM 2 replication on two harder clips",
        question: "Does the racket silhouette survive different backgrounds and scale?",
        result: "One clip failed because the seed included the ball; one repeated clip stayed attached but did not establish new-frame continuity.",
        implication: "Seed purity and source cadence dominate downstream memory.",
        status: "failed",
      },
      {
        method: "SAM 2 prompt ablation",
        question: "Would box, point, or mixed prompts turn SAM 2 into a general racket tracker?",
        result: "All prompt types ended at the same 3/5 clips; wall/background and tiny-racket failures persisted.",
        implication: "Prompt tuning was closed as the next lever.",
        status: "failed",
      },
      {
        method: "Cutie memory tracker",
        question: "Would a materially different memory model repair SAM 2 failures?",
        result: "Also finished at 3/5 clips. It removed one detached line but preserved background already included in the initial mask.",
        implication: "A different tracker cannot repair a wrong observation.",
        status: "failed",
      },
      {
        method: "TAPNext++ ball replication",
        question: "Can an independent point tracker reproduce the ball result?",
        result: "Passed the clear clip at 55/57 within 8 px, 1.56 px median and 4.77 px p90; improved a repeated clip but failed the clipped edge case.",
        implication: "The clear-clip ball result is independently reproducible, not general.",
        status: "survived",
      },
      {
        method: "Grounding DINO racket discovery",
        question: "Can open-vocabulary detection at least locate the real racket automatically?",
        result: "Found the actual racket in all 5/5 frozen observations, including the prior wall-prompt failure.",
        implication: "Keep the detector as a proposal stage.",
        status: "survived",
      },
      {
        method: "Box-only SAM 2 seed",
        question: "Is a correct detector box sufficient for a clean racket mask?",
        result: "Passed only 1/5; hand, wrist, ball, spectator, and background were absorbed.",
        implication: "Detection and instance separation are different problems.",
        status: "failed",
      },
      {
        method: "YOLOE instance separation",
        question: "Can open-vocabulary segmentation produce a cleaner initial racket mask?",
        result: "Two of five masks stayed clean for 177/177 frames; three fused with hand, body, or background.",
        implication: "A clean seed propagates; generic masks are not reliably clean.",
        status: "partial",
      },
      {
        method: "RacketVision + YOLOE + SAM 2 hybrid",
        question: "Can a fixed gate choose the better automatic seed per clip?",
        result: "Selected RacketVision on 3/5 and YOLOE on 2/5, but still passed only 2/5 clips and 177/415 frames—the same as YOLOE alone.",
        implication: "More routing logic added no net evidence.",
        status: "failed",
      },
      {
        method: "Official RacketVision validation",
        question: "Does the released checkpoint work in its own tennis domain?",
        result: "Detected 28/28 official validation rackets with 0.845 median box IoU and 84.96% PCK@0.1.",
        implication: "The release itself works in-domain.",
        status: "survived",
      },
      {
        method: "RacketVision on five external observations",
        question: "Does that in-domain quality transfer to our frozen sources?",
        result: "Produced coherent five-point geometry on only 3/5 observations; two collapsed or displaced.",
        implication: "External-style racket data, not another threshold, is the missing lever.",
        status: "failed",
      },
      {
        method: "Box-only pseudo-label pilot",
        question: "Can independent automatic teachers create training masks without hand labels?",
        result: "Produced 0/48 strict-clean racket masks.",
        implication: "No training was allowed from contaminated labels.",
        status: "failed",
      },
      {
        method: "Racket-keypoints + SAM 2 pseudo-label pilot",
        question: "Do released racket keypoints improve the mask corpus enough to train?",
        result: "Improved to 18/48 strict-clean, but tiny rackets were 0/12 and the 36/48 training gate failed.",
        implication: "Automatic pseudo-label training remained unsafe.",
        status: "failed",
      },
      {
        method: "SAM 2.1 Tiny versus Large",
        question: "Was model capacity the cause of the failed masks?",
        result: "Both finished at exactly 18/48 clean; Large was 4.302× slower and the first full-process run died after 30/48.",
        implication: "Bigger segmentation compute changed zero verdicts.",
        status: "failed",
      },
      {
        method: "Structured racket-shaped seed",
        question: "Would an ellipse head plus shaft prompt preserve the complete racket?",
        result: "Passed 0/248 frames and 0/8 clips; SAM rewrote the seed toward the stringbed and lost shaft/handle.",
        implication: "Prompt geometry was closed.",
        status: "failed",
      },
      {
        method: "Human-complete polygon seed",
        question: "Would one correct full racket silhouette unlock temporal propagation?",
        result: "Eight accepted human masks still produced 0/240 strict-clean held-out frames and 0/8 passing clips.",
        implication: "One-frame correction is insufficient; dense labels or marked capture are next.",
        status: "failed",
        artifact: "/media/human-mask-failure-review.mp4",
      },
      {
        method: "Independent per-frame RacketVision",
        question: "Can temporal failure be avoided by reconstructing each frame independently?",
        result: "Detected 248/248, passed automatic topology on 118/248, and human inspection accepted 75/248; 0/8 clips passed continuity.",
        implication: "Useful proposal frames, not a continuous racket layer.",
        status: "failed",
        artifact: "/media/per-frame-racket-review.mp4",
      },
      {
        method: "Rigid 2D racket composition",
        question: "Can accepted per-frame anchors become one watchable constant-shape racket with only bounded interpolation?",
        result: "All 29 frames passed visual continuity, but anchor p95 was 16.136 px against a frozen 15 px gate.",
        implication: "Useful authored teaching overlay; one measurable fidelity gate still failed.",
        status: "partial",
        artifact: "/media/rigid-2d-composition.mp4",
      },
    ],
  },
  {
    title: "Corpus, metrics, and reversals",
    scope: "Tests that changed what could be claimed, even when they did not produce a prettier demo.",
    attempts: [
      {
        method: "Large public-source harvest",
        question: "Can scale solve the footage problem?",
        result: "1,424 candidates → 379 screened → 98 curated and downloaded; only 41.9% of the evaluated pose subset supported any defensible quantity.",
        implication: "Harvesting more internet video multiplies unusable footage; controlled capture has higher leverage.",
        status: "partial",
      },
      {
        method: "SigLIP 2 semantic frame retrieval",
        question: "Can review scale without replacing human evidence checks?",
        result: "Embedded 1,568 frames and found the correct frame for all four initial text queries at 129 frames/s on MPS.",
        implication: "Keep as retrieval and triage, never as a measurement oracle.",
        status: "survived",
      },
      {
        method: "Proximal-to-distal ordering test",
        question: "Can broadcast footage recover the serve sequence?",
        result: "Ordering held in 29.6% of 27 gated reps, at or below chance.",
        implication: "The headline biomechanics claim was retired for this corpus.",
        status: "failed",
      },
      {
        method: "Peak-failure re-slice",
        question: "Was frame quantization alone causing the ordering failure?",
        result: "Only 22% of reps had truly sub-frame lag; large errors mostly came from choosing different noisy peaks, not merely low frame rate.",
        implication: "The negative result survived, but its causal explanation was corrected.",
        status: "retracted",
      },
      {
        method: "Torso-size usability gate",
        question: "Does torso ≥90 px identify usable clips?",
        result: "Misclassified 37.2% of 86 clips and was removed as a hard abort.",
        implication: "A convenient gate was not load-bearing.",
        status: "retracted",
      },
      {
        method: "Playback-rate contamination test",
        question: "Did spatial normalization remove slow-motion speed differences?",
        result: "Normalized speed had Spearman rho = −1.00 with playback slowdown.",
        implication: "Every speed, duration, and rate claim dies without the native clock.",
        status: "failed",
      },
      {
        method: "Axial-observability claim audit",
        question: "Was axial rotation truly 0% observable?",
        result: "No. The zero came from a gating bug; remeasurement found 89.8% finite observability within ±2 s, while the values still failed model-agreement gates.",
        implication: "The 0% headline was retracted; the weaker conclusion—monocular axial estimates are unstable—remains.",
        status: "retracted",
      },
      {
        method: "Kovacs law adjudicability census",
        question: "How much coaching doctrine can the internet corpus actually test?",
        result: "0/11 laws admitted a fresh test on the old corpus; five become testable with controlled capture, three need more, and three are not video questions.",
        implication: "Use doctrine as a measurement agenda, not as evidence for its own claims.",
        status: "survived",
      },
      {
        method: "Evidence-state visual grammar",
        question: "Can measured, computed, inferred, interpreted, and source claims remain distinguishable at scale?",
        result: "The grammar was tested across 41 cards, contrast failures and vocabulary collisions were corrected, and tamper tests caught drift.",
        implication: "Evidence origin, observability, verdict, and release verification must remain separate dimensions.",
        status: "survived",
      },
    ],
  },
];

export const literature = [
  ["TT3D", "Table-tennis ball, scene calibration, bounce physics, and spin", "Best visible proof that a physics fit plus reprojection can turn sparse ball observations into a coherent 3D rally. It does not solve player or racket pose.", "https://arxiv.org/abs/2504.10035"],
  ["Uplifting Table Tennis", "Noisy 2D ball observations → physically credible 3D", "Best ball-layer QA blueprint: detection, filtering, lifting, physics, and reprojection shown separately.", "https://kiedani.github.io/WACV2026/"],
  ["Vid2Player3D", "Reusable physics-trained tennis player", "Best long-term player/controller precedent; trained weights are withheld and close grip/contact truth is not proved.", "https://research.nvidia.com/labs/toronto-ai/vid2player3d/"],
  ["GEM-X / GENMO", "Expressive monocular body recovery", "Current executed body baseline; reusable body sequence, no independent racket or ball.", "https://github.com/NVlabs/GEM-X"],
  ["SOMA-X", "Identity/motion representation and retargeting", "Useful infrastructure for persistent bodies; compatibility does not validate source motion.", "https://github.com/NVlabs/SOMA-X"],
  ["MAMMA", "Calibrated multi-view body reconstruction", "Best open owned-capture body ceiling; still requires independent racket and ball layers.", "https://mamma.is.tue.mpg.de/"],
  ["FoundationPose", "Novel rigid-object 6D pose", "Correct artifact class for a racket, but thin fast symmetric rackets need markers, CAD, depth/calibration, and contact checks.", "https://github.com/NVlabs/FoundationPose"],
  ["Open4DHOI", "Monocular human–object reconstruction", "The closest research framing for hand/racket coupling; sparse contact annotation remains necessary.", "https://wenboran2002.github.io/open4dhoi/"],
  ["RacketVision", "Racket-sport ball and articulated racket benchmark", "Most relevant benchmark lineage; in-domain validation did not transfer cleanly to all external observations.", "https://ojs.aaai.org/index.php/AAAI/article/view/37362"],
  ["BlurBall", "Fast blurred-ball observations", "Treats blur as motion evidence rather than detector failure; front end only, not 3D or spin.", "https://openaccess.thecvf.com/content/CVPR2026W/CVsports/html/Gossard_BlurBall_Joint_Ball_and_Motion_Blur_Estimation_for_Table_Tennis_CVPRW_2026_paper.html"],
  ["SAM-Body4D", "Temporally repaired body meshes", "Strong same-source body challenger once gated assets and CUDA are available; body only.", "https://arxiv.org/abs/2512.08406"],
  ["WHAM / GVHMR", "World-grounded monocular body motion", "Important root/world-motion lineage; neither removes racket, ball, grip, or contact ambiguity.", "https://wham.is.tue.mpg.de/"],
] as const;

export const statusLabel: Record<AttemptStatus, string> = {
  survived: "kept",
  partial: "bounded result",
  failed: "stopped",
  blocked: "not executed",
  retracted: "corrected",
};
